name: ilac_hatirlatici
description: İlaç hatırlatma uygulaması
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
